### ISSUE TITLE
Release latest changes

### ISSUE THREAD

**Issue by BendingBender** [mazira/base64-stream#8]
Thank you for the great package!

The problem: I've read the docs, downloaded the package via `npm` and started using it just to get an error about `Base64Encode` not being a constructor. Digging into the source and commit log for this package, I've found out that the interface has changed and the docs in the readme describe the unreleased interface. Looking up the version in the `package.json` didn't even help because it is the same as on `npm` (what I usually do first, before looking into commit logs).

Would you mind to release the new package version, possibly as a new major version? Or at least change the version in the `package.json` to make clear that the version in `master` branch is a different one from that on `npm`.

**Comment by rossj** [comment]
Better late than never? 1.0.0 is out!
